### ISSUE TITLE
Throws file not found despite main executable clearly being there

### ISSUE THREAD

**Issue by Juff-Ma** [kuiperzone/PupNet-Deploy#12]
It throws a file not found for the main executable (on windows and linux), i checked and the file is there, definitely and runs fine

on linux:
Building Package ...
```
Exists?: AppDir/Publish/PupNetTest ... FAILED

FAILED
File not found /tmp/KuiperZone.PupNet/de.juffma.pupnettest-linux-x64-Release-Zip/AppDir/Publish/PupNetTest
```

on Windows:

Building Package ...
```
Exists?: AppDir\Publish\PupNetTest.exe ... FAILED

FAILED
File not found C:\Users\Julian\AppData\Local\Temp\KuiperZone.PupNet\de.juffma.pupnettest-win-x64-Release-Setup\AppDir\Publish\PupNetTest.exe
```

**Comment by kuiperzone** [comment]
Any chance you could zip up your test project and attach it below? I'll take a look.

**Comment by kuiperzone** [comment]
Make sure you include your pupnet.conf file.

**Comment by Juff-Ma** [comment]
Yes, it's a test project based on Eto.Forms quickly thrown together
[PubNetTest.zip](https://github.com/kuiperzone/PupNet-Deploy/files/11413047/PubNetTest.zip)

**Comment by kuiperzone** [comment]
Your application in conf file is called:

AppBaseName = PupNetTest

but your project (and its output) is called: PubNetTest

nb. p != b

However, I'm glad you posted because I found a couple of other problems:

AppImage is not building because it is not finding an icon (you haven't provided one but my test code does). It should instead use a default icon and this used to work but looks like there is now a problem.

Flatpak is failing because it doesn't like the fact there is a <releases> element, but no children because you have not provided an AppChangeFile whereas my test code does.

I'll be release a patch shortly.

Thank you

**Comment by Juff-Ma** [comment]
Oh, it seems i mistyped there. Thats my fault. thanks for the help anyway and if you found some other problems it wasn't that bad

**Comment by kuiperzone** [comment]
Try version 1.4.1. Your project builds OK with this.

If youre installing from Nuget, give it half hour before 1.4.1 become available.

I'm glad you posted. I made a few changes recently, and you helped me shake out hidden bugs.
