### ISSUE TITLE
Problems displaying other languages ​​when building Avalonia version 11.0.5 for linux-x64

### ISSUE THREAD

**Issue by Walli-DO** [kuiperzone/PupNet-Deploy#34]
When building Avalonia version 11.0.5 for linux-x64, in some places text written in a language other than English is displayed incorrectly. However, this problem does not appear if you create an installer for Windows. However, this problem does not occur in all places; in some places the text display is normal, but in others it is erroneous. Please tell me what could be the cause of the problem
![Screenshot](https://github.com/kuiperzone/PupNet-Deploy/assets/163833385/46b3fdcb-e12d-4664-a0f2-15c888d70ff1)

**Comment by kuiperzone** [comment]
Hi Walli,

You don't mention whether you are building AppImage, flatpak, RPM or DEB. The screenshot is not something I can recognise. I can't help but suspect that this is an issue with Avalonia issue or your app not displaying correctly on Linux, rather than an installer issue?

I would suggest to try publishing your app directly from command line (without PupNet - just `dotnet publish`), and see if the problem still occurs.

If not, check if you need any or don't need any `publish` arguments and compare with PupNet is calling publish with, which are displayed to you during the pupnet build. More on arguments here:

https://github.com/kuiperzone/PupNet-Deploy?tab=readme-ov-file#dotnet-publish-arguments

**Comment by Walli-DO** [comment]
Got it, thanks, I'll do that. I created an AppImage, I’ll test it, just do everything via dotnet publish

**Comment by Walli-DO** [comment]
I found what the problem was, the files were saved in the wrong encoding (not in utf-8), but in the encoding intended for the Russian language pack, which logically should be displayed that way, but problems occur with this
